# Generated by Django 6.0.6 on 2026-07-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_useractivestrategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='app_pin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
