# Generated by Django 6.0.6 on 2026-07-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_app_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='app_pin',
        ),
    ]
