# Generated by Django 5.1.7 on 2026-07-28 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_customuser_app_pin_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='botlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
